# Generated by Django 4.2.6 on 2023-10-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_remove_clientdata_message_clientdata_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='email',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='city',
            field=models.CharField(default=' ', max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
    ]
