# Generated by Django 4.2.6 on 2023-10-18 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_alter_image_options_alter_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
